repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      python-version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: flake8
      name: flake8
      python-version: python3.6
      files: ^(uplink_protobuf|tests)\/.+\.py$
