language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
before_script:
  - pip install tox
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install flake8 flake8-bugbear; fi
script:
  - tox -e py
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then flake8 uplink_protobuf tests setup.py; fi
after_success:
  - pip install codecov
  - codecov